Update
- beautify the Patch application a bit (synced with the llvm-git package), sync patches

diff --git a/toolchain-experimental/lib32-llvm-git/PKGBUILD b/toolchain-experimental/lib32-llvm-git/PKGBUILD
--- a/toolchain-experimental/lib32-llvm-git/PKGBUILD
+++ b/toolchain-experimental/lib32-llvm-git/PKGBUILD
@@ -15,7 +15,7 @@
 pkgbase=lib32-llvm-git
 pkgname=(lib32-llvm-git lib32-llvm-libs-git)
 pkgdesc="Collection of modular and reusable compiler and toolchain technologies (32-bit, git)"
-pkgver=16.0.0_r435476.df868edee561
+pkgver=16.0.0_r436718.37c6a25e9ab2
 pkgrel=1
 arch=('x86_64')
 url='https://llvm.org/'
@@ -25,6 +25,7 @@ source=("llvm-project::git+https://github.com/llvm/llvm-project.git"
         corecount.patch
         fmafusion.patch
         haswell.patch
+        improve-kernel-compile.patch
         )
 sha512sums=('SKIP')
 
@@ -36,33 +37,45 @@ _python_optimize() {
 
 pkgver() {
     cd llvm-project/llvm
-
     # This will almost match the output of `llvm-config --version` when the
     # LLVM_APPEND_VC_REV cmake flag is turned on. The only difference is
     # dash being replaced with underscore because of Pacman requirements.
     local _pkgver=$(awk -F 'MAJOR |MINOR |PATCH |)' \
             'BEGIN { ORS="." ; i=0 } \
              /set\(LLVM_VERSION_/ { print $2 ; i++ ; if (i==2) ORS="" } \
-             END { print "\n" }' \
-             CMakeLists.txt)_r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)
-    echo "${_pkgver//svn}"
+            END { print "\n" }' \
+        CMakeLists.txt)_r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)
+    echo "$_pkgver"
+}
+
+_rpatch() {
+
+    echo -e "\E[1;33m Revert patch: ${1}\E[0m"
+    patch --forward --reverse --strip=1 --input="${srcdir:?}/${1}"
+
+}
+
+_patch() {
+
+    echo -e "\E[1;33m Apply patch: ${1}\E[0m"
+    patch --forward --strip=1 --input="${srcdir:?}/${1}"
+
 }
 
 prepare() {
-    # although removing _build folder in build() function feels more natural,
-    # that interferes with the spirit of makepkg --noextract
-    if [  -d _build ]; then
-        rm -rf _build
-    fi
 
-    local src
-    for src in "${source[@]}"; do
-        src="${src%%::*}"
-        src="${src##*/}"
-        [[ $src = *.patch ]] || continue
-        echo "Applying patch $src..."
-        patch --directory="llvm-project" --forward --strip=1 < "../$src"
-    done
+    cd "${srcdir:?}/llvm-project" || (
+        echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Prepare Failed! \E[0m"
+        exit 1
+    )
+
+    _patch corecount.patch
+    _patch fmafusion.patch
+    _patch haswell.patch
+    _patch improve-kernel-compile.patch
+    # Attempt to convert script to Python 3
+    2to3 -wn --no-diffs \
+        clang-tools-extra/clang-include-fixer/find-all-symbols/tool/run-find-all-symbols.py
 
 }
 
@@ -87,9 +100,9 @@ build() {
         -D LLVM_DEFAULT_TARGET_TRIPLE="i686-pc-linux-gnu" \
         -D CMAKE_BUILD_TYPE=Release \
         -D BUILD_SHARED_LIBS:BOOL=OFF \
-        -D CMAKE_EXE_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=mold -Wl,-zcommon-page-size=0x200000 -m32 -Wl,-zmax-page-size=0x200000" \
-        -D CMAKE_MODULE_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=mold -Wl,-zcommon-page-size=0x200000 -m32 -Wl,-zmax-page-size=0x200000" \
-        -D CMAKE_SHARED_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=mold -Wl,-zcommon-page-size=0x200000 -m32 -Wl,-zmax-page-size=0x200000" \
+        -D CMAKE_EXE_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=lld -m32" \
+        -D CMAKE_MODULE_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=lld -m32" \
+        -D CMAKE_SHARED_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=lld -m32" \
         -D CMAKE_INSTALL_PREFIX=/usr \
         -D LLVM_BINUTILS_INCDIR=/usr/include \
         -D LLVM_APPEND_VC_REV=ON \
