Introduce new LLVM-git PKGBUILD
... thanks to ptr1337, for testing some new ideas and recommended upstream changes

diff --git a/toolchain-experimental/llvm-git/PKGBUILD b/toolchain-experimental/llvm-git/PKGBUILD
--- a/toolchain-experimental/llvm-git/PKGBUILD
+++ b/toolchain-experimental/llvm-git/PKGBUILD
@@ -1,117 +1,141 @@
-# Maintainer: Marcus Seyfarth <marcus85@gmx.de>
-# Contributor: Reza Jahanbakhshi <reza.jahanbakhshi at gmail dot com
-# Contributor: Lone_Wolf <lone_wolf@klaas-de-kat.nl>
-# Contributor: yurikoles <root@yurikoles.com>
-# Contributor: bearoso <bearoso@gmail.com>
-# Contributor: Luchesar V. ILIEV <luchesar%2eiliev%40gmail%2ecom>
-# Contributor: Anders Bergh <anders@archlinuxppc.org>
-# Contributor: Armin K. <krejzi at email dot com>
-# Contributor: Christian Babeux <christian.babeux@0x80.ca>
-# Contributor: Jan "heftig" Steffens <jan.steffens@gmail.com>
-# Contributor: Evangelos Foutras <evangelos@foutrelis.com>
-# Contributor: Hesiod (https://github.com/hesiod)
-# Contributor: Roberto Alsina <ralsina@kde.org>
-# Contributor: Thomas Dziedzic < gostrc at gmail >
-# Contributor: Tomas Lindquist Olsen <tomas@famolsen.dk>
-# Contributor: Tomas Wilhelmsson <tomas.wilhelmsson@gmail.com>
 
-
-pkgname=('llvm-git' 'llvm-libs-git')
-pkgver=16.0.0_r435476.df868edee561
+pkgname=llvm-git
+pkgdesc="LLVM Toolchain with clang, clang-tools-extra, compiler-rt, openmp, polly, lldb, lld"
+pkgver=16.0.0_r436661.e0cdafe8d4b2
 pkgrel=1
 arch=('x86_64')
 url="https://llvm.org/"
 license=('custom:Apache 2.0 with LLVM Exception')
-makedepends=('git' 'cmake' 'ninja' 'libffi' 'libedit' 'ncurses' 'libxml2' 'python-sphinx'
-             'python-sphinx-automodapi' 'lldb' 'ocaml' 'ocaml-ctypes' 'ocaml-findlib'
-             'python-sphinx' 'python-recommonmark' 'swig' 'python' 'python-six' 'lua53'
-             'ocl-icd' 'opencl-headers' 'z3' 'jsoncpp' 'ocaml-stdlib-shims' 'llvm' 'llvm-libs' 'clang' 'lld')
-checkdepends=("python-psutil")
-source=("llvm-project::git+https://github.com/llvm/llvm-project.git"
-        "llvm-config.h"
-        corecount.patch
-        fmafusion.patch
-        haswell.patch
-        )
 
-md5sums=('SKIP'
-         '295c343dcd457dc534662f011d7cff1a')
-sha512sums=('SKIP'
-            '75e743dea28b280943b3cc7f8bbb871b57d110a7f2b9da2e6845c1c36bf170dd883fca54e463f5f49e0c3effe07fbd0db0f8cf5a12a2469d3f792af21a73fcdd')
-options=('staticlibs' 'strip')
+provides=('aur-llvm-git' 'compiler-rt-git' 'clang-git' 'lld-git' 'polly-git' 'aur-llvm-libs-git'
+		  'llvm-libs' 'polly-git' 'openmp-git' 'pstl-git'
+		  'llvm' 'compiler-rt' 'clang' 'polly' 'lld' 'openmp' 'pstl' 'libc++' 'libc++abi' 'libc++experimental')
+# A package always provides itself, so there's no need to provide llvm-git
+conflicts=('llvm' 'compiler-rt' 'clang' 'polly' 'lld' 'llvm-libs' 'openmp' 'pstl' 'libc++abi' 'libc++experimental' 'libc++')
+depends=('libelf' 'libffi' 'libedit' 'libxml2' 'ncurses')
+_ocaml_ver=4.13.1
+makedepends=(
+    'git' 'ninja' 'cmake'
+    "ocaml>=${_ocaml_ver}" 'ocaml-ctypes' 'ocaml-findlib'
+    'python-setuptools' 'python-psutil' 'python-sphinx'
+    'python-recommonmark' 'clang' 'lld' 'llvm-libs' 'llvm' 'mold'
+)
+makedepends_x86_64=('lib32-gcc-libs')
+source=(
+    "llvm-project::git+https://github.com/llvm/llvm-project.git"
+    'llvm-config.h'
+    'improve-kernel-compile.patch'
+    'corecount.patch'
+    'fmafusion.patch'
+    'haswell.patch'
+)
 
-# NINJAFLAGS is an env var used to pass commandline options to ninja
-# NOTE: It's your responbility to validate the value of $NINJAFLAGS. If unsure, don't set it.
-# NINJAFLAGS="-j20"
+sha256sums=('SKIP'
+            '597dc5968c695bbdbb0eac9e8eb5117fcd2773bc91edf5ec103ecffffab8bc48'
+            '593ed385298623711070dffce9225cb448dfc29f30c9d950887882b19bd124fb')
 
-_python_optimize() {
-  python -m compileall "$@"
-  python -O -m compileall "$@"
-  python -OO -m compileall "$@"
-}
+options=('staticlibs')
 
 pkgver() {
     cd llvm-project/llvm
-
     # This will almost match the output of `llvm-config --version` when the
     # LLVM_APPEND_VC_REV cmake flag is turned on. The only difference is
     # dash being replaced with underscore because of Pacman requirements.
     local _pkgver=$(awk -F 'MAJOR |MINOR |PATCH |)' \
             'BEGIN { ORS="." ; i=0 } \
              /set\(LLVM_VERSION_/ { print $2 ; i++ ; if (i==2) ORS="" } \
-             END { print "\n" }' \
-             CMakeLists.txt)_r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)
+            END { print "\n" }' \
+        CMakeLists.txt)_r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)
     echo "$_pkgver"
 }
 
-prepare() {
-    # although removing _build folder in build() function feels more natural,
-    # that interferes with the spirit of makepkg --noextract
-    if [  -d _build ]; then
-        rm -rf _build
-    fi
+_rpatch() {
 
-    local src
-    for src in "${source[@]}"; do
-        src="${src%%::*}"
-        src="${src##*/}"
-        [[ $src = *.patch ]] || continue
-        echo "Applying patch $src..."
-        patch --directory="llvm-project" --forward --strip=1 < "../$src"
-    done
+    echo -e "\E[1;33m Revert patch: ${1}\E[0m"
+    patch --forward --reverse --strip=1 --input="${srcdir:?}/${1}"
+
+}
+
+_patch() {
+
+    echo -e "\E[1;33m Apply patch: ${1}\E[0m"
+    patch --forward --strip=1 --input="${srcdir:?}/${1}"
+
+}
+
+prepare() {
+
+    cd "${srcdir:?}/llvm-project" || (
+        echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Prepare Failed! \E[0m"
+        exit 1
+    )
+
+    _patch corecount.patch
+    _patch fmafusion.patch
+    _patch haswell.patch
+    _patch improve-kernel-compile.patch
+    # Attempt to convert script to Python 3
+    2to3 -wn --no-diffs \
+        clang-tools-extra/clang-include-fixer/find-all-symbols/tool/run-find-all-symbols.py
 
 }
 
 build() {
 
-    export CFLAGS=${CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
-    export CXXFLAGS=${CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
+    cd "${srcdir:?}/llvm-project" || (
+        echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Build Failed! \E[0m"
+        exit 1
+    )
 
-    cmake \
-        -B _build \
-        -S "$srcdir"/llvm-project/llvm  \
-        -G Ninja \
-        -D CMAKE_BUILD_TYPE=Release \
-        -D BUILD_SHARED_LIBS:BOOL=OFF \
+    if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]"; then
+        export CC=clang
+        export CXX=clang++
+        export AR=llvm-ar
+        export AS=llvm-as
+        export NM=llvm-nm
+        export STRIP=llvm-strip
+        export OBJCOPY=llvm-objcopy
+        export OBJDUMP=llvm-objdump
+        export READELF=llvm-readelf
+        export HOSTCC=clang
+        export HOSTCXX=clang++
+        export HOSTAR=llvm-ar
+        export DEBUG_CFLAGS="-g"
+        export DEBUG_CXXFLAGS="-g"
+        _extra_build_flags+=(
+            -DCMAKE_C_COMPILER=clang
+            -DCMAKE_CXX_COMPILER=clang++
+        )
+    else
+        echo -e "\E[1;31mClang not found. Will use default system compiler! \E[0m"
+    fi
+
+    if ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
+        export LD=ld.lld
+        export CC_LD=lld
+        export CXX_LD=lld
+        export HOSTLD=ld.lld
+        _extra_build_flags+=(-DLLVM_USE_LINKER=lld)
+    fi
+
+    cmake -S llvm -B build -G Ninja \
+        -DCMAKE_BUILD_TYPE=Release \
+        -DCMAKE_INSTALL_PREFIX=/usr \
+        -DLLVM_BINUTILS_INCDIR=/usr/include \
+        -DLLVM_HOST_TRIPLE="${CHOST:?}" \
+        -DLLVM_BUILD_RUNTIME=ON \
+        -DLLVM_BUILD_LLVM_DYLIB=ON \
+        -DLLVM_LINK_LLVM_DYLIB=ON \
+        -DCLANG_LINK_CLANG_DYLIB=ON \
+        -DLLVM_INSTALL_UTILS=ON \
+        -DLLVM_ENABLE_RTTI=ON \
+        -DLLVM_ENABLE_FFI=ON \
+        -DLLVM_ENABLE_BINDINGS=OFF \
         -D CMAKE_C_FLAGS="$CFLAGS -g0 -Wp,-D_FORTIFY_SOURCE=0" \
         -D CMAKE_CXX_FLAGS="$CXXFLAGS -g0 -Wp,-D_FORTIFY_SOURCE=0" \
-        -D CMAKE_EXE_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=mold -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000" \
-        -D CMAKE_MODULE_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=mold -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000" \
-        -D CMAKE_SHARED_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=mold -Wl,-zcommon-page-size=0x200000 -Wl,-zmax-page-size=0x200000" \
-        -D CMAKE_INSTALL_PREFIX=/usr \
-        -D LLVM_BINUTILS_INCDIR=/usr/include \
-        -D LLVM_APPEND_VC_REV=ON \
-        -D LLVM_VERSION_SUFFIX="" \
-        -D LLVM_HOST_TRIPLE=$CHOST \
-        -D LLVM_ENABLE_RTTI=ON \
-        -D LLVM_ENABLE_FFI=ON \
-        -D FFI_INCLUDE_DIR:PATH="$(pkg-config --variable=includedir libffi)" \
-        -D LLVM_TARGETS_TO_BUILD="AMDGPU;X86" \
-        -D LLVM_BUILD_LLVM_DYLIB:BOOL=ON \
-        -D LLVM_LINK_LLVM_DYLIB:BOOL=ON \
-        -D CLANG_LINK_CLANG_DYLIB=ON \
-        -D LLVM_BUILD_TOOLS:BOOL=ON \
-        -D LLVM_BUILD_UTILS:BOOL=ON \
+        -D CMAKE_EXE_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=lld" \
+        -D CMAKE_MODULE_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=lld" \
+        -D CMAKE_SHARED_LINKER_FLAGS="-Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -flto -fuse-ld=lld" \
         -D LLVM_INCLUDE_BENCHMARKS=OFF \
         -D LLVM_INCLUDE_GO_TESTS=OFF \
         -D LLVM_INCLUDE_TESTS=OFF \
@@ -121,76 +145,89 @@ build() {
         -D LLVM_ENABLE_OCAMLDOC=OFF \
         -D LLVM_ENABLE_SPHINX=OFF \
         -D LLVM_ENABLE_DOXYGEN=OFF \
-        -D LLVM_ENABLE_BINDINGS=OFF \
-        -D POLLY_ENABLE_GPGPU_CODEGEN=OFF \
-        -D LLVM_POLLY_LINK_INTO_TOOLS=ON \
-        -D LLVM_ENABLE_ZLIB:BOOL=ON \
-        -D LLVM_ENABLE_PROJECTS="polly;lld;clang;compiler-rt;openmp" \
-        -Wno-dev
+        -DLLVM_POLLY_LINK_INTO_TOOLS=ON \
+        -DLLVM_TARGETS_TO_BUILD="AMDGPU;X86;NVPTX" \
+        -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;polly;pstl" \
+        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;openmp;compiler-rt" \
+        -DRUNTIMES_CMAKE_ARGS=-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF \
+        -DCLANG_LINK_CLANG_DYLIB=ON \
+        -DLIBOMP_INSTALL_ALIASES=OFF \
+        -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF \
+        -DPOLLY_ENABLE_GPGPU_CODEGEN=ON \
+        -DCLANG_DEFAULT_PIE_ON_LINUX=OFF \
+        "${_extra_build_flags[@]}"
 
-    ninja -C _build $NINJAFLAGS
+    ninja -C build
+
 }
 
-package_llvm-git() {
-    pkgdesc="LLVM development version. includes clang and many other tools"
-    depends=("llvm-libs-git=$pkgver-$pkgrel" 'perl')
-    optdepends=('python: for scripts'
-                'python-setuptools: for using lit = LLVM Integrated Tester'
+_python_optimize() {
+    python -m compileall "$@"
+    python -O -m compileall "$@"
+    python -OO -m compileall "$@"
+}
+
+package() {
+
+    cd "${srcdir:?}/llvm-project" || (
+        echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Package Failed! \E[0m"
+        exit 1
     )
-    provides=(aur-llvm-git compiler-rt-git clang-git openmp-git lld-git polly-git
-              llvm compiler-rt clang openmp polly lld )
-    options=('strip')
 
-    DESTDIR="$pkgdir" ninja -C _build $NINJAFLAGS install
-
-    _py="3.10"
-    cd llvm-project
-
-    # Fix permissions of static libs
-    chmod -x "$pkgdir"/usr/lib/*.a
-
-    # Move scanbuild-py into site-packages and install Python bindings
-    local site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
-    install -d "$pkgdir/$site_packages"
-    #mv "$pkgdir"/usr/lib/{libear,libscanbuild} "$pkgdir/$site_packages/"
-    cp -a ${srcdir}/llvm-project/clang/bindings/python/clang "$pkgdir/$site_packages/"
-
-    # Move analyzer scripts out of /usr/libexec
-    #mv "$pkgdir"/usr/libexec/* "$pkgdir/usr/lib/clang/"
-    #rmdir "$pkgdir/usr/libexec"
-    #sed -i 's|libexec|lib/clang|' \
-    #"$pkgdir/usr/bin/scan-build" \
-    #"$pkgdir/$site_packages/libscanbuild/analyze.py"
-
-    # Compile Python scripts
-    _python_optimize "$pkgdir/usr/share" "$pkgdir/$site_packages"
-
-    # The runtime libraries go into llvm-libs
-    mv -f "$pkgdir"/usr/lib/lib{LLVM,LTO,Remarks}*.so* "$srcdir"
-    mv -f "$pkgdir"/usr/lib/LLVMgold.so "$srcdir"
-
-    if [[ $CARCH == x86_64 ]]; then
-        # Needed for multilib (https://bugs.archlinux.org/task/29951)
-        # Header stub is taken from Fedora
-        mv "$pkgdir/usr/include/llvm/Config/llvm-config"{,-64}.h
-        cp "$srcdir/llvm-config.h" "$pkgdir/usr/include/llvm/Config/llvm-config.h"
+    if [[ _build_documentation -eq 0 ]]; then
+        mkdir -p "${srcdir:?}/llvm-project/build/docs/ocamldoc/html/"
     fi
-}
 
-package_llvm-libs-git() {
-    pkgdesc="runtime libraries for llvm-git"
-    depends=('gcc-libs' 'zlib' 'libffi' 'libedit' 'ncurses' 'libxml2')
-    provides=(aur-llvm-libs-git llvm-libs)
-    options=('strip')
+    DESTDIR="${pkgdir:?}" ninja -C build install
 
-    install -d "$pkgdir"/usr/lib
-    cp -P \
-        "$srcdir"/lib{LLVM,LTO,Remarks}*.so* \
-        "$srcdir"/LLVMgold.so \
-        "$pkgdir"/usr/lib/
+    pushd llvm/utils/lit || (
+        echo -e "\E[1;31mpushd utils/lit - Package Failed! \E[0m"
+        exit 1
+    )
+
+    python setup.py install --root="${pkgdir:?}" -O1
+    popd || (
+        echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
+        exit 1
+    )
+
+    if [[ "${CARCH:?}" == "x86_64" ]]; then
+        mv "${pkgdir:?}/usr/include/llvm/Config/llvm-config"{,-64}.h
+        cp "${srcdir:?}/llvm-config.h" "${pkgdir:?}/usr/include/llvm/Config/llvm-config.h"
+    fi
 
     # Symlink LLVMgold.so from /usr/lib/bfd-plugins
     # https://bugs.archlinux.org/task/28479
-    install -d "$pkgdir/usr/lib/bfd-plugins"
-    ln -s ../LLVMgold.so "$pkgdir/usr/lib/bfd-plugins/LLVMgold.so"
+    mkdir -p "${pkgdir:?}/usr/lib/bfd-plugins"
+    ln -s ../LLVMgold.so "${pkgdir:?}/usr/lib/bfd-plugins/LLVMgold.so"
+
+    # Clang
+    site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
+    install -d "${pkgdir:?}/${site_packages}"
+    mv "${pkgdir:?}/usr/lib/"{libear,libscanbuild} "${pkgdir:?}/${site_packages}/"
+    cp -a llvm/bindings/python/llvm "${pkgdir:?}/${site_packages}/"
+    cp -a clang/bindings/python/clang "${pkgdir:?}/${site_packages}/"
+
+    mv "${pkgdir:?}"/usr/libexec/* "${pkgdir:?}/usr/lib/clang/"
+    rm -fr "${pkgdir:?}/usr/libexec"
+    sed -i 's|libexec|lib/clang|' \
+        "${pkgdir:?}/usr/bin/scan-build" \
+        "${pkgdir:?}/${site_packages}/libscanbuild/analyze.py"
+
+    _python_optimize "${pkgdir:?}/usr/share" "${pkgdir:?}/${site_packages}"
+
+    # Remove html documentation
+    if [[ _build_documentation -eq 0 ]]; then
+        rm -fr "${pkgdir:?}/usr/share/doc"
+    fi
+
+    # Licenses
+    install -Dm644 "${srcdir:?}/llvm-project/llvm/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/llvm-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/clang/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/clang-tools-extra/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-tools-extra-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/compiler-rt/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/compiler-rt-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/lld/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/lld-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/polly/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/polly-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/openmp/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/openmp-LICENSE"
+
 }
