Update llvm
- see lib32-package for rationale

diff --git a/toolchain-experimental/llvm-git/PKGBUILD b/toolchain-experimental/llvm-git/PKGBUILD
--- a/toolchain-experimental/llvm-git/PKGBUILD
+++ b/toolchain-experimental/llvm-git/PKGBUILD
@@ -14,10 +14,10 @@ conflicts=('llvm' 'compiler-rt' 'clang' 'polly' 'lld' 'llvm-libs' 'openmp' 'pstl
 depends=('libelf' 'libffi' 'libedit' 'libxml2' 'ncurses')
 _ocaml_ver=5.0.0
 makedepends=(
-    'git' 'ninja' 'cmake'
+    'git' 'ninja' 'cmake' 'z3'
     "ocaml>=${_ocaml_ver}" 'ocaml-ctypes' 'ocaml-findlib' 'ocaml-stdlib-shims'
     'python-setuptools' 'python-psutil'
-    'python-recommonmark' 'clang' 'lld' 'llvm-libs' 'llvm' 'mold'
+    'python-recommonmark' 'clang' 'lld' 'llvm-libs' 'llvm'
 )
 makedepends_x86_64=('lib32-gcc-libs')
 source=(
@@ -36,16 +36,26 @@ sha256sums=('SKIP'
 options=('staticlibs')
 
 pkgver() {
-    cd llvm-project/llvm
-    # This will almost match the output of `llvm-config --version` when the
-    # LLVM_APPEND_VC_REV cmake flag is turned on. The only difference is
-    # dash being replaced with underscore because of Pacman requirements.
-    local _pkgver=$(awk -F 'MAJOR |MINOR |PATCH |)' \
-            'BEGIN { ORS="." ; i=0 } \
-             /set\(LLVM_VERSION_/ { print $2 ; i++ ; if (i==2) ORS="" } \
-            END { print "\n" }' \
-        CMakeLists.txt)_r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)
-    echo "$_pkgver"
+
+  cd "${srcdir:?}/llvm-project" || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! PkgVer Failed! \E[0m"
+    exit 1
+  )
+
+  _gitdesc=$(git describe --long --tags)
+  if [[ "${_gitdesc}" =~ "rc" ]]; then
+    _gitdesc="_$(echo "${_gitdesc}" | cut -f3-4 -d- | sed -e 's/\-/+r/')"
+  else
+    _gitdesc="+r$(echo "${_gitdesc}" | cut -f3 -d-)"
+  fi
+
+  echo "$(
+    sed -nE "/LLVM_VERSION_MAJOR/{:a;N;/LLVM_VERSION_SUFFIX/Ta};0,/LLVM_VERSION_MAJOR/D;p" \
+      llvm/CMakeLists.txt |
+      grep -oP "\d+" |
+      xargs | tr ' ' '.'
+  )${_gitdesc}"
+
 }
 
 _rpatch() {
@@ -152,6 +162,7 @@ build() {
         -D LLVM_ENABLE_ZLIB=ON \
         -D LLVM_ENABLE_ZSTD=ON \
         -D LIBCLANG_BUILD_STATIC=ON \
+	-D LLVM_ENABLE_Z3_SOLVER=ON \
         -DLIBOMP_INSTALL_ALIASES=ON \
         -DLIBOMP_ENABLE_SHARED=ON \
         -DOPENMP_ENABLE_LIBOMP_PROFILING=OFF \
