Update mpfr with CS-PGO

diff --git a/packages/mpfr/PKGBUILD b/packages/mpfr/PKGBUILD
--- a/packages/mpfr/PKGBUILD
+++ b/packages/mpfr/PKGBUILD
@@ -11,8 +11,8 @@ if (( _patchver == 0 )); then
 else
   pkgver=$_pkgver.p$_patchver
 fi
-pkgrel=3.1
-pkgdesc='Multiple-precision floating-point library'
+pkgrel=2.1
+pkgdesc='Multiple-precision floating-point library (aggressive PGO + CS-PGO)'
 arch=(x86_64)
 url='https://www.mpfr.org/'
 license=(
@@ -23,16 +23,205 @@ depends=(
   glibc
   gmp
 )
+makedepends=(
+  clang
+  llvm
+)
+options=(!lto !debug)
 provides=(libmpfr.so)
+
 # NOTE: download potentially existing patches from upstream:
-# `curl patches.diff -o https://www.mpfr.org/mpfr-${_pkgver}/allpatches`
+# `curl https://www.mpfr.org/mpfr-${_pkgver}/allpatches -o patches.diff`
 source=(https://ftp.gnu.org/gnu/$pkgname/$pkgname-$_pkgver.tar.xz{,.sig})
-sha512sums=('bc68c0d755d5446403644833ecbb07e37360beca45f474297b5d5c40926df1efc3e2067eecffdf253f946288bcca39ca89b0613f545d46a9e767d1d4cf358475'
+sha512sums=('eb9e7f51b5385fb349cc4fba3a45ffdf0dd53be6dfc74932dc01258158a10514667960c530c47dd9dfc5aa18be2bd94859d80499844c5713710581e6ac6259a9'
             'SKIP')
-b2sums=('ad69f53bc910294647523e7613b18a683f1d0f3dd994168ab2a46b66d0371ffa9b8e7cb59495f898470aea69d343e83fc722f11babe4af7b3a12665a1e65860c'
+b2sums=('6bbf5658e70fbb673a3b65246a6bac708d1571aa6943c6742efd92f468ac71e6f0fe351b757f7133440ea312d9a5fc3549acd89d54f4d975c58bdc204d7b21ec'
         'SKIP')
 validpgpkeys=('07F3DBBECC1A39605078094D980C197698C3739D'
               'A534BE3F83E241D918280AEB5831D11A0D4DB02A') # Vincent Lefevre <vincent@vinc17.net>
+
+_profile_use_silence=(
+  -Wno-profile-instr-out-of-date
+  -Wno-profile-instr-unprofiled
+)
+
+_split_flags() {
+  local varname="$1"
+  local -n out_ref="$2"
+  out_ref=()
+  [[ -n ${!varname:-} ]] && read -r -a out_ref <<< "${!varname}"
+}
+
+_configure_mpfr() {
+  local builddir="$1"
+  local cflags="$2"
+  local cppflags="$3"
+  local ldflags="$4"
+
+  mkdir -p "$builddir"
+  pushd "$builddir" >/dev/null
+  CFLAGS="$cflags" \
+  CPPFLAGS="$cppflags" \
+  LDFLAGS="$ldflags" \
+  "$srcdir/$pkgname-$_pkgver/configure" \
+    --prefix=/usr \
+    --enable-thread-safe \
+    --enable-shared
+  popd >/dev/null
+}
+
+_build_mpfr() {
+  local builddir="$1"
+  make -C "$builddir"
+}
+
+_reset_profraw_dir() {
+  local dir="$1"
+  rm -rf "$dir"
+  mkdir -p "$dir"
+}
+
+_collect_profraw() {
+  local outvar="$1"
+  shift
+  local -n out_ref="$outvar"
+  local path
+
+  out_ref=()
+  for path in "$@"; do
+    [[ -d "$path" ]] || continue
+    while IFS= read -r -d '' f; do
+      out_ref+=("$f")
+    done < <(find "$path" -type f -name '*.profraw' -print0)
+  done
+}
+
+_write_training_workload() {
+  local outfile="$1"
+  cat > "$outfile" <<'EOF'
+#include <gmp.h>
+#include <mpfr.h>
+#include <stdint.h>
+#include <stdio.h>
+#include <stdlib.h>
+
+static void hot_loop(gmp_randstate_t rs, mpfr_prec_t prec, int rounds) {
+  mpfr_t a, b, c, d;
+  mpfr_rnd_t modes[] = {MPFR_RNDN, MPFR_RNDZ, MPFR_RNDU, MPFR_RNDD, MPFR_RNDA};
+  const size_t mode_count = sizeof(modes) / sizeof(modes[0]);
+
+  mpfr_init2(a, prec);
+  mpfr_init2(b, prec);
+  mpfr_init2(c, prec);
+  mpfr_init2(d, prec);
+
+  for (int i = 1; i <= rounds; ++i) {
+    mpfr_rnd_t rnd = modes[(unsigned)i % mode_count];
+    mpfr_urandomb(a, rs);
+    mpfr_urandomb(b, rs);
+    mpfr_urandomb(c, rs);
+    mpfr_add_d(b, b, 0.125 + (double)(i & 7), rnd);
+    mpfr_add_d(c, c, 1.0 + (double)(i % 13), rnd);
+
+    switch (i & 15) {
+      case 0:
+        mpfr_add(d, a, b, rnd);
+        break;
+      case 1:
+        mpfr_sub(d, a, b, rnd);
+        break;
+      case 2:
+        mpfr_mul(d, a, c, rnd);
+        break;
+      case 3:
+        mpfr_div(d, c, b, rnd);
+        break;
+      case 4:
+        mpfr_sqrt(d, c, rnd);
+        break;
+      case 5:
+        mpfr_exp(d, a, rnd);
+        break;
+      case 6:
+        mpfr_log(d, c, rnd);
+        break;
+      case 7:
+        mpfr_sin(d, c, rnd);
+        break;
+      case 8:
+        mpfr_cos(d, c, rnd);
+        break;
+      case 9:
+        mpfr_tan(d, c, rnd);
+        break;
+      case 10:
+        mpfr_atan2(d, a, b, rnd);
+        break;
+      case 11:
+        mpfr_pow(d, c, b, rnd);
+        break;
+      case 12:
+        mpfr_hypot(d, a, b, rnd);
+        break;
+      case 13:
+        mpfr_fma(d, a, b, c, rnd);
+        break;
+      case 14:
+        mpfr_const_pi(d, rnd);
+        break;
+      default:
+        mpfr_gamma(d, c, rnd);
+        break;
+    }
+
+    mpfr_swap(a, d);
+  }
+
+  mpfr_clears(a, b, c, d, (mpfr_ptr)0);
+}
+
+int main(void) {
+  gmp_randstate_t rs;
+  mpfr_prec_t precs[] = {53, 64, 80, 106, 128, 192, 256, 384, 512, 768, 1024, 2048};
+  int rounds[] = {35000, 30000, 30000, 25000, 25000, 20000, 16000, 12000, 9000, 7000, 5000, 3000};
+  const size_t count = sizeof(precs) / sizeof(precs[0]);
+
+  gmp_randinit_mt(rs);
+  gmp_randseed_ui(rs, 0xC0FFEEu);
+
+  for (size_t i = 0; i < count; ++i)
+    hot_loop(rs, precs[i], rounds[i]);
+
+  gmp_randclear(rs);
+  return 0;
+}
+EOF
+}
+
+_run_profile_workload() {
+  local builddir="$1"
+  local stage="$2"
+  local profdir="$3"
+  local libdir="$builddir/src/.libs"
+  local src_c="$srcdir/mpfr-pgo-workload.c"
+  local bin="$srcdir/mpfr-pgo-workload"
+  local profile_file="$profdir/mpfr-%p-%m.profraw"
+
+  _write_training_workload "$src_c"
+  clang -O3 -march=x86-64-v3 -I"$srcdir/$pkgname-$_pkgver/src" "$src_c" \
+    -L"$libdir" -Wl,-rpath,"$libdir" -lmpfr -lgmp -lm -o "$bin"
+
+  # Blend synthetic arithmetic hotspots with upstream's broad functional tests.
+  LLVM_PROFILE_FILE="$profile_file" \
+    LD_LIBRARY_PATH="$libdir:${LD_LIBRARY_PATH:-}" timeout 120s "$bin"
+  LLVM_PROFILE_FILE="$profile_file" make -C "$builddir" -j1 check
+  LLVM_PROFILE_FILE="$profile_file" make -C "$builddir" -j1 check-exported-symbols
+
+  if [[ "$stage" == 2 ]]; then
+    LLVM_PROFILE_FILE="$profile_file" \
+      LD_LIBRARY_PATH="$libdir:${LD_LIBRARY_PATH:-}" timeout 90s "$bin"
+  fi
+}
 
 prepare() {
   cd $pkgname-${_pkgver}
@@ -47,20 +236,98 @@ prepare() {
 }
 
 build() {
-  cd $pkgname-${_pkgver}
-  ./configure --prefix=/usr \
-    --enable-thread-safe \
-    --enable-shared
-  make
+  export CC=clang
+  export CXX=clang++
+  export AR=llvm-ar
+  export NM=llvm-nm
+  export RANLIB=llvm-ranlib
+
+  local -a base_cppflags=()
+  local -a base_cflags=()
+  local -a base_ldflags=()
+
+  _split_flags CPPFLAGS base_cppflags
+  _split_flags CFLAGS base_cflags
+  _split_flags LDFLAGS base_ldflags
+
+  local -a debugmap_flags=(
+    "-ffile-prefix-map=$srcdir=/usr/src/debug/$pkgname"
+    "-fdebug-prefix-map=$srcdir=/usr/src/debug/$pkgname"
+    "-fmacro-prefix-map=$srcdir=/usr/src/debug/$pkgname"
+  )
+
+  local build_pgo="$srcdir/build-pgo"
+  local build_cspgo="$srcdir/build-cspgo"
+  local build_final="$srcdir/build-final"
+  local pgo_raw="$srcdir/pgo_raw"
+  local cspgo_raw="$srcdir/cs_pgo_raw"
+  local prof_stage1="$srcdir/prof_stage1.prof"
+  local prof_final="$srcdir/prof_final.prof"
+
+  rm -rf "$build_pgo" "$build_cspgo" "$build_final" \
+         "$pgo_raw" "$cspgo_raw" "$prof_stage1" "$prof_final"
+
+  local base_cppflags_str="${base_cppflags[*]}"
+  local base_cflags_str="${base_cflags[*]}"
+  local base_ldflags_str="${base_ldflags[*]}"
+  local debugmap_flags_str="${debugmap_flags[*]}"
+
+  echo "-> Stage 1: Building PGO-instrumented mpfr..."
+  _reset_profraw_dir "$pgo_raw"
+  local pgo_cflags="$base_cflags_str $debugmap_flags_str -fprofile-generate -fprofile-update=atomic"
+  local pgo_cppflags="$base_cppflags_str"
+  local pgo_ldflags="$base_ldflags_str -fprofile-generate"
+
+  _configure_mpfr "$build_pgo" "$pgo_cflags" "$pgo_cppflags" "$pgo_ldflags"
+  _build_mpfr "$build_pgo"
+
+  echo "-> Stage 1: Running comprehensive profile workload..."
+  _run_profile_workload "$build_pgo" 1 "$pgo_raw"
+
+  local -a pgo_raws=()
+  _collect_profraw pgo_raws "$pgo_raw" "$build_pgo" "$srcdir/$pkgname-$_pkgver"
+  (( ${#pgo_raws[@]} )) || {
+    echo "Error: no Stage 1 profile data produced." >&2
+    return 1
+  }
+  llvm-profdata merge -sparse -output="$prof_stage1" "${pgo_raws[@]}"
+  llvm-profdata show --counts --all-functions "$prof_stage1" >/dev/null
+
+  echo "-> Stage 2: Building CS-PGO-instrumented mpfr..."
+  _reset_profraw_dir "$cspgo_raw"
+  local cspgo_cflags="$base_cflags_str $debugmap_flags_str -fcs-profile-generate -fprofile-update=atomic -fprofile-use=$prof_stage1 ${_profile_use_silence[*]}"
+  local cspgo_cppflags="$base_cppflags_str"
+  local cspgo_ldflags="$base_ldflags_str -fcs-profile-generate -fprofile-use=$prof_stage1"
+
+  _configure_mpfr "$build_cspgo" "$cspgo_cflags" "$cspgo_cppflags" "$cspgo_ldflags"
+  _build_mpfr "$build_cspgo"
+
+  echo "-> Stage 2: Running comprehensive profile workload..."
+  _run_profile_workload "$build_cspgo" 2 "$cspgo_raw"
+
+  local -a cspgo_raws=()
+  _collect_profraw cspgo_raws "$cspgo_raw" "$build_cspgo" "$srcdir/$pkgname-$_pkgver"
+  (( ${#cspgo_raws[@]} )) || {
+    echo "Error: no Stage 2 profile data produced." >&2
+    return 1
+  }
+  llvm-profdata merge -sparse -output="$prof_final" "$prof_stage1" "${cspgo_raws[@]}"
+  llvm-profdata show --counts --all-functions "$prof_final" >/dev/null
+
+  echo "-> Stage 3: Building final optimized mpfr..."
+  local final_cflags="$base_cflags_str $debugmap_flags_str -fprofile-use=$prof_final ${_profile_use_silence[*]}"
+  local final_cppflags="$base_cppflags_str"
+  local final_ldflags="$base_ldflags_str -fprofile-use=$prof_final"
+
+  _configure_mpfr "$build_final" "$final_cflags" "$final_cppflags" "$final_ldflags"
+  _build_mpfr "$build_final"
 }
 
 check() {
-  cd $pkgname-${_pkgver}
-  make check
-  make check-exported-symbols
+  make -C "$srcdir/build-final" -j1 check
+  make -C "$srcdir/build-final" -j1 check-exported-symbols
 }
 
 package() {
-  cd $pkgname-${_pkgver}
-  make DESTDIR="$pkgdir" install
+  make -C "$srcdir/build-final" DESTDIR="$pkgdir" install
 }
