Update libmpc with CS-PGO

diff --git a/packages/libmpc/PKGBUILD b/packages/libmpc/PKGBUILD
--- a/packages/libmpc/PKGBUILD
+++ b/packages/libmpc/PKGBUILD
@@ -2,37 +2,305 @@
 # Contributor: Allan McRae <allan@archlinux.org>
 
 pkgname=libmpc
-pkgver=1.3.1
-pkgrel=3.1
-pkgdesc='Library for the arithmetic of complex numbers with arbitrarily high precision'
+pkgver=1.4.1
+pkgrel=2.1
+pkgdesc='Library for the arithmetic of complex numbers with arbitrarily high precision (PGO + CS-PGO optimized)'
 arch=(x86_64)
 url='http://www.multiprecision.org/'
-license=(LGPL)
-depends=(mpfr)
-source=(https://ftp.gnu.org/gnu/mpc/mpc-${pkgver/_/-}.tar.gz{,.sig}
-        )
-sha256sums=('0e3b12181d37207230f5a7a7ddcfc22abfc5fc9c05825e1a65401a489a432a2a'
-            'SKIP'
-            '998032f3a42a6774970464ad7a8dd47d028b5da601dbe11c7853485a1dc85509')
+license=(LGPL-3.0-only)
+depends=(
+  glibc
+  gmp
+  mpfr
+)
+makedepends=(
+  clang
+  llvm
+)
+options=(!lto !debug)
+source=(https://ftp.gnu.org/gnu/mpc/mpc-${pkgver/_/-}.tar.xz{,.sig})
+sha256sums=('91204cd32f164bd3b7c992d4a6a8ce6519511aadab30f78b6982d0bf8d73e931'
+            'SKIP')
 validpgpkeys=('AD17A21EF8AED8F1CC02DBD9F7D5C9BF765C61E3')  # Andreas Enge
 
-prepare() {
-  cd mpc-$pkgver
+_profile_use_silence=(
+  -Wno-profile-instr-out-of-date
+  -Wno-profile-instr-unprofiled
+)
+
+_split_flags() {
+  local varname="$1"
+  local -n out_ref="$2"
+  out_ref=()
+  [[ -n ${!varname:-} ]] && read -r -a out_ref <<< "${!varname}"
+}
+
+_configure_mpc() {
+  local builddir="$1"
+  local cflags="$2"
+  local cppflags="$3"
+  local ldflags="$4"
+
+  mkdir -p "$builddir"
+  pushd "$builddir" >/dev/null
+  CFLAGS="$cflags" \
+  CPPFLAGS="$cppflags" \
+  LDFLAGS="$ldflags" \
+  "$srcdir/mpc-$pkgver/configure" \
+    --prefix=/usr
+  popd >/dev/null
+}
+
+_build_mpc() {
+  local builddir="$1"
+  make -C "$builddir"
+}
+
+_reset_profraw_dir() {
+  local dir="$1"
+  rm -rf "$dir"
+  mkdir -p "$dir"
+}
+
+_collect_profraw() {
+  local outvar="$1"
+  shift
+  local -n out_ref="$outvar"
+  local path
+
+  out_ref=()
+  for path in "$@"; do
+    [[ -d "$path" ]] || continue
+    while IFS= read -r -d '' f; do
+      out_ref+=("$f")
+    done < <(find "$path" -type f -name '*.profraw' -print0)
+  done
+}
+
+_write_training_workload() {
+  local outfile="$1"
+  cat > "$outfile" <<'EOF'
+#include <gmp.h>
+#include <mpfr.h>
+#include <mpc.h>
+#include <stddef.h>
+
+static void run_hot_loop(gmp_randstate_t rs, mpfr_prec_t prec, int rounds) {
+  mpc_t a, b, c, d;
+  mpc_rnd_t rnds[] = {
+    MPC_RNDNN,
+    MPC_RNDNZ,
+    MPC_RNDDN,
+    MPC_RNDZN,
+    MPC_RNDUU
+  };
+  const size_t rnd_count = sizeof(rnds) / sizeof(rnds[0]);
+
+  mpc_init2(a, prec);
+  mpc_init2(b, prec);
+  mpc_init2(c, prec);
+  mpc_init2(d, prec);
+
+  for (int i = 1; i <= rounds; ++i) {
+    mpc_rnd_t rnd = rnds[(unsigned)i % rnd_count];
+    mpc_urandom(a, rs);
+    mpc_urandom(b, rs);
+    mpc_add_ui(c, b, (unsigned long)(i & 31), rnd);
+
+    switch (i & 15) {
+      case 0:
+        mpc_add(d, a, c, rnd);
+        break;
+      case 1:
+        mpc_sub(d, a, c, rnd);
+        break;
+      case 2:
+        mpc_mul(d, a, c, rnd);
+        break;
+      case 3:
+        mpc_div(d, c, a, rnd);
+        break;
+      case 4:
+        mpc_sqr(d, c, rnd);
+        break;
+      case 5:
+        mpc_sqrt(d, c, rnd);
+        break;
+      case 6:
+        mpc_exp(d, a, rnd);
+        break;
+      case 7:
+        mpc_log(d, c, rnd);
+        break;
+      case 8:
+        mpc_sin(d, c, rnd);
+        break;
+      case 9:
+        mpc_cos(d, c, rnd);
+        break;
+      case 10:
+        mpc_tan(d, c, rnd);
+        break;
+      case 11:
+        mpc_pow(d, c, a, rnd);
+        break;
+      case 12:
+        mpc_proj(d, c, rnd);
+        break;
+      case 13:
+        mpc_conj(d, c, rnd);
+        break;
+      case 14:
+        mpc_asin(d, c, rnd);
+        break;
+      default:
+        mpc_acos(d, c, rnd);
+        break;
+    }
+
+    mpc_swap(a, d);
+  }
+
+  mpc_clear(a);
+  mpc_clear(b);
+  mpc_clear(c);
+  mpc_clear(d);
+}
+
+int main(void) {
+  gmp_randstate_t rs;
+  mpfr_prec_t precs[] = {53, 64, 80, 128, 192, 256, 384, 512, 768, 1024};
+  int rounds[] = {40000, 36000, 32000, 26000, 22000, 18000, 14000, 10000, 7000, 4500};
+  const size_t count = sizeof(precs) / sizeof(precs[0]);
+
+  gmp_randinit_mt(rs);
+  gmp_randseed_ui(rs, 0xB16B00B5u);
+
+  for (size_t i = 0; i < count; ++i)
+    run_hot_loop(rs, precs[i], rounds[i]);
+
+  gmp_randclear(rs);
+  return 0;
+}
+EOF
+}
+
+_run_profile_workload() {
+  local builddir="$1"
+  local stage="$2"
+  local profdir="$3"
+  local libdir="$builddir/src/.libs"
+  local src_c="$srcdir/libmpc-pgo-workload.c"
+  local bin="$srcdir/libmpc-pgo-workload"
+  local profile_file="$profdir/libmpc-%p-%m.profraw"
+
+  _write_training_workload "$src_c"
+  clang -O3 -march=x86-64-v3 -I"$srcdir/mpc-$pkgver/src" "$src_c" \
+    -L"$libdir" -Wl,-rpath,"$libdir" -lmpc -lmpfr -lgmp -lm -o "$bin"
+
+  LLVM_PROFILE_FILE="$profile_file" \
+    LD_LIBRARY_PATH="$libdir:${LD_LIBRARY_PATH:-}" timeout 120s "$bin"
+  LLVM_PROFILE_FILE="$profile_file" make -C "$builddir" -j1 check
+
+  if [[ "$stage" == 2 ]]; then
+    LLVM_PROFILE_FILE="$profile_file" \
+      LD_LIBRARY_PATH="$libdir:${LD_LIBRARY_PATH:-}" timeout 90s "$bin"
+  fi
 }
 
 build() {
-  cd mpc-$pkgver
-  ./configure --prefix=/usr
-  make
+  export CC=clang
+  export CXX=clang++
+  export AR=llvm-ar
+  export NM=llvm-nm
+  export RANLIB=llvm-ranlib
+
+  local -a base_cppflags=()
+  local -a base_cflags=()
+  local -a base_ldflags=()
+
+  _split_flags CPPFLAGS base_cppflags
+  _split_flags CFLAGS base_cflags
+  _split_flags LDFLAGS base_ldflags
+
+  local -a debugmap_flags=(
+    "-ffile-prefix-map=$srcdir=/usr/src/debug/$pkgname"
+    "-fdebug-prefix-map=$srcdir=/usr/src/debug/$pkgname"
+    "-fmacro-prefix-map=$srcdir=/usr/src/debug/$pkgname"
+  )
+
+  local build_pgo="$srcdir/build-pgo"
+  local build_cspgo="$srcdir/build-cspgo"
+  local build_final="$srcdir/build-final"
+  local pgo_raw="$srcdir/pgo_raw"
+  local cspgo_raw="$srcdir/cs_pgo_raw"
+  local prof_stage1="$srcdir/prof_stage1.prof"
+  local prof_final="$srcdir/prof_final.prof"
+
+  rm -rf "$build_pgo" "$build_cspgo" "$build_final" \
+         "$pgo_raw" "$cspgo_raw" "$prof_stage1" "$prof_final"
+
+  local base_cppflags_str="${base_cppflags[*]}"
+  local base_cflags_str="${base_cflags[*]}"
+  local base_ldflags_str="${base_ldflags[*]}"
+  local debugmap_flags_str="${debugmap_flags[*]}"
+
+  echo "-> Stage 1: Building PGO-instrumented libmpc..."
+  _reset_profraw_dir "$pgo_raw"
+  local pgo_cflags="$base_cflags_str $debugmap_flags_str -fprofile-generate -fprofile-update=atomic"
+  local pgo_cppflags="$base_cppflags_str"
+  local pgo_ldflags="$base_ldflags_str -fprofile-generate"
+
+  _configure_mpc "$build_pgo" "$pgo_cflags" "$pgo_cppflags" "$pgo_ldflags"
+  _build_mpc "$build_pgo"
+
+  echo "-> Stage 1: Running comprehensive profile workload..."
+  _run_profile_workload "$build_pgo" 1 "$pgo_raw"
+
+  local -a pgo_raws=()
+  _collect_profraw pgo_raws "$pgo_raw" "$build_pgo" "$srcdir/mpc-$pkgver"
+  (( ${#pgo_raws[@]} )) || {
+    echo "Error: no Stage 1 profile data produced." >&2
+    return 1
+  }
+  llvm-profdata merge -sparse -output="$prof_stage1" "${pgo_raws[@]}"
+  llvm-profdata show --counts --all-functions "$prof_stage1" >/dev/null
+
+  echo "-> Stage 2: Building CS-PGO-instrumented libmpc..."
+  _reset_profraw_dir "$cspgo_raw"
+  local cspgo_cflags="$base_cflags_str $debugmap_flags_str -fcs-profile-generate -fprofile-update=atomic -fprofile-use=$prof_stage1 ${_profile_use_silence[*]}"
+  local cspgo_cppflags="$base_cppflags_str"
+  local cspgo_ldflags="$base_ldflags_str -fcs-profile-generate -fprofile-use=$prof_stage1"
+
+  _configure_mpc "$build_cspgo" "$cspgo_cflags" "$cspgo_cppflags" "$cspgo_ldflags"
+  _build_mpc "$build_cspgo"
+
+  echo "-> Stage 2: Running comprehensive profile workload..."
+  _run_profile_workload "$build_cspgo" 2 "$cspgo_raw"
+
+  local -a cspgo_raws=()
+  _collect_profraw cspgo_raws "$cspgo_raw" "$build_cspgo" "$srcdir/mpc-$pkgver"
+  (( ${#cspgo_raws[@]} )) || {
+    echo "Error: no Stage 2 profile data produced." >&2
+    return 1
+  }
+  llvm-profdata merge -sparse -output="$prof_final" "$prof_stage1" "${cspgo_raws[@]}"
+  llvm-profdata show --counts --all-functions "$prof_final" >/dev/null
+
+  echo "-> Stage 3: Building final optimized libmpc..."
+  local final_cflags="$base_cflags_str $debugmap_flags_str -fprofile-use=$prof_final ${_profile_use_silence[*]}"
+  local final_cppflags="$base_cppflags_str"
+  local final_ldflags="$base_ldflags_str -fprofile-use=$prof_final"
+
+  _configure_mpc "$build_final" "$final_cflags" "$final_cppflags" "$final_ldflags"
+  _build_mpc "$build_final"
 }
 
 check() {
-  cd mpc-$pkgver
-  make check
+  make -C "$srcdir/build-final" -j1 check
 }
 
 package() {
-  cd mpc-$pkgver
-  make DESTDIR="$pkgdir" install
+  make -C "$srcdir/build-final" DESTDIR="$pkgdir" install
   mv "$pkgdir"/usr/share/info/{mpc,libmpc}.info
 }
