Update systemd

diff --git a/packages/systemd/systemd-hook b/packages/systemd/systemd-hook
--- a/packages/systemd/systemd-hook
+++ b/packages/systemd/systemd-hook
@@ -1,93 +1,86 @@
-#!/bin/sh -e
+#!/bin/sh
+set -e
 
-skip_chrooted() {
-  if systemd-detect-virt --chroot >/dev/null 2>&1; then
+_chroot_check() {
+  if systemd-detect-virt --chroot; then
     echo >&2 "  Skipped: Running in chroot."
     exit 0
   fi
 }
 
-systemd_live() {
-  skip_chrooted
-
-  if ! systemctl is-system-running >/dev/null 2>&1; then
-    echo >&2 "  Skipped: Current root is not booted."
+_systemd_live() {
+  _chroot_check
+  if ! systemctl --version &>/dev/null || ! systemd-notify --booted; then
+    echo >&2 "  Skipped: Current root is not booted with systemd."
     exit 0
   fi
 }
 
-udevd_live() {
-  skip_chrooted
-
+_udevd_live() {
+  _systemd_live
   if [ ! -S /run/udev/control ]; then
     echo >&2 "  Skipped: Device manager is not running."
     exit 0
   fi
 }
 
-op="$1"; shift
+op="${1:?Operation required}"; shift
 
 case "$op" in
-  binfmt)
-    systemd_live
-    /usr/lib/systemd/systemd-binfmt
-    ;;
-  catalog)
-    /usr/bin/journalctl --update-catalog
-    ;;
-  daemon-reload-system)
-    systemd_live
-    /usr/bin/systemctl --system daemon-reload
-    ;;
-  daemon-reload-user)
-    systemd_live
-    /usr/bin/systemctl reload 'user@*.service'
-    ;;
-  hwdb)
-    /usr/bin/systemd-hwdb --usr update
-    ;;
-  sysctl)
-    systemd_live
-    /usr/lib/systemd/systemd-sysctl
-    ;;
   sysusers)
     /usr/bin/systemd-sysusers
     ;;
   tmpfiles)
     /usr/bin/systemd-tmpfiles --create
     ;;
-  update)
-    touch -c /usr
+  binfmt)
+    _systemd_live
+    /usr/lib/systemd/systemd-binfmt
+    ;;
+  catalog)
+    /usr/bin/journalctl --update-catalog
+    ;;
+  hwdb)
+    /usr/bin/systemd-hwdb --usr update
+    ;;
+  sysctl)
+    _systemd_live
+    /usr/lib/systemd/systemd-sysctl
+    ;;
+  daemon-reload-system)
+    _systemd_live
+    /usr/bin/systemctl --system daemon-reload
+    ;;
+  daemon-reload-user)
+    _systemd_live
+    /usr/bin/systemctl reload 'user@*.service' || true
+    ;;
+  restart-marked)
+    _systemd_live
+    /usr/bin/systemctl reload-or-restart --marked
     ;;
   udev-reload)
-    udevd_live
+    _udevd_live
     /usr/bin/udevadm control --reload
     if [ ! -e /etc/systemd/do-not-udevadm-trigger-on-update ]; then
-      /usr/bin/udevadm trigger -c change
+      /usr/bin/udevadm trigger --type=subsystems --action=change
+      /usr/bin/udevadm trigger --type=devices --action=change
       /usr/bin/udevadm settle
     fi
     ;;
-
-  # marked with 'systemctl set-property ... Markers=needs-restart'
-  restart-marked)
-    systemd_live
-    /usr/bin/systemctl reload-or-restart --marked
+  update)
+    touch -c /usr
     ;;
-
-  # For use by other packages
   reload)
-    systemd_live
+    _systemd_live
     /usr/bin/systemctl try-reload-or-restart "$@"
     ;;
-
-  # For use by other packages
   restart)
-    systemd_live
+    _systemd_live
     /usr/bin/systemctl try-restart "$@"
     ;;
-
   *)
-    echo >&2 "  Invalid operation '$op'"
+    echo >&2 "  Invalid operation: '$op'"
     exit 1
     ;;
 esac
